SELECT * FROM SALES ORDER BY AMOUNT

SELECT MIN(AMOUNT),MAX(AMOUNT),COUNT(ID), SUM (AMOUNT), AVG(AMOUNT) FROM SALES 


SELECT * FROM SALES ORDER BY TOTALPRICE

SELECT SUM(TOTALPRICE) FROM SALES


SELECT MIN(TOTALPRICE), MAX(TOTALPRICE), COUNT(ID), SUM(TOTALPRICE), AVG(TOTALPRICE) FROM SALES WHERE CITY = 'ÝSTANBUL'
  
SELECT MIN(TOTALPRICE), MAX(TOTALPRICE), COUNT(ID), SUM(TOTALPRICE), AVG(TOTALPRICE) FROM SALES WHERE CITY = 'ANKARA'