SELECT * FROM CUSTOMERS WHERE CITY = 'ÝSTANBUL' AND DISTRICT = 'BEYLÝKDÜZÜ' AND GENDER = 'KADIN'

SELECT * FROM CUSTOMERS WHERE DISTRICT = 'ESENLER'

SELECT * FROM CUSTOMERS WHERE CITY = 'ÝSTANBUL' AND GENDER = 'ERKEK' AND BIRTHDATE BETWEEN '19900101' AND '20000101'

