SELECT MIN(TOTALPRICE), MAX(TOTALPRICE), COUNT(ID), SUM(TOTALPRICE), AVG(TOTALPRICE) 
FROM SALES WHERE CITY = 'ÝSTANBUL'
  
SELECT MIN(TOTALPRICE), MAX(TOTALPRICE), COUNT(ID), SUM(TOTALPRICE), AVG(TOTALPRICE) 
FROM SALES WHERE CITY = 'ANKARA'

SELECT MIN(TOTALPRICE), MAX(TOTALPRICE), COUNT(ID), SUM(TOTALPRICE), AVG(TOTALPRICE) 
FROM SALES WHERE CITY = 'ÝZMÝR'


SELECT 
CITY,
MIN(TOTALPRICE) AS MINPRICE, MAX(TOTALPRICE) AS MAXPRICE, COUNT(ID) AS ROWCOUNT_ , SUM(TOTALPRICE) AS TOTALPRICE, AVG(TOTALPRICE) AS AVGPRICE
FROM SALES 
GROUP BY CITY ORDER BY SUM(TOTALPRICE)



SELECT TOP 10
CITY, SUM(TOTALPRICE) AS TOTALPRICE
FROM SALES 
GROUP BY CITY ORDER BY SUM(TOTALPRICE) DESC