SELECT CATEGORY1,CATEGORY2,CATEGORY3,CATEGORY4,
SUM(TOTALPRICE) AS TOTALPRICE,
COUNT(*) AS ROWCOUNT_,
SUM(AMOUNT) AS TOTALAMOUNT


FROM SALES
GROUP BY CATEGORY1,CATEGORY2,CATEGORY3,CATEGORY4
ORDER BY CATEGORY1,CATEGORY2,CATEGORY3,CATEGORY4





SELECT CATEGORY1,CATEGORY2,
SUM(TOTALPRICE) AS TOTALPRICE,
COUNT(*) AS ROWCOUNT_,
SUM(AMOUNT) AS TOTALAMOUNT


FROM SALES
GROUP BY CATEGORY1,CATEGORY2
ORDER BY CATEGORY1,CATEGORY2




SELECT CATEGORY1,
SUM(TOTALPRICE) AS TOTALPRICE,
COUNT(*) AS ROWCOUNT_,
SUM(AMOUNT) AS TOTALAMOUNT


FROM SALES
GROUP BY CATEGORY1
ORDER BY CATEGORY1






SELECT CATEGORY4,
SUM(TOTALPRICE) AS TOTALPRICE,
COUNT(*) AS ROWCOUNT_,
SUM(AMOUNT) AS TOTALAMOUNT


FROM SALES
GROUP BY CATEGORY4
ORDER BY CATEGORY4