SELECT * FROM CUSTOMERS WHERE CITY = 'ÝSTANBUL' OR CITY  = 'ÝZMÝR' OR CITY = 'BURSA'

SELECT * FROM CUSTOMERS WHERE CITY = 'ÝSTANBULXXX' OR CITY  = 'ÝZMÝR' OR CITY = 'BURSA'

SELECT * FROM CUSTOMERS WHERE CITY IN ('ÝSTANBUL','ÝZMÝR', 'ANTALYA') 


--YORUM SATIRI
SELECT * FROM CUSTOMERS -- WHERE BIRTHDATE BETWEEN '19900101' AND '19981231' 

SELECT * FROM CUSTOMERS WHERE NOT BIRTHDATE <= '19900101'  OR BIRTHDATE >= '19981231' 

SELECT * FROM CUSTOMERS WHERE NOT BIRTHDATE BETWEEN '19900101' AND '19981231' 
