SELECT * FROM CUSTOMERS 

SELECT * FROM CUSTOMERS ORDER BY ID DESC

SELECT * FROM CUSTOMERS ORDER BY CUSTOMERNAME ASC  -- ALFABETÝK, A-Z

SELECT * FROM CUSTOMERS ORDER BY AGE DESC

SELECT * FROM CUSTOMERS  WHERE CITY = 'ADANA' ORDER BY DISTRICT ASC  

SELECT * FROM CUSTOMERS ORDER BY CITY,CUSTOMERNAME DESC

SELECT * FROM CUSTOMERS WHERE CITY = 'ÝSTANBUL' ORDER BY CITY, DISTRICT, CUSTOMERNAME

SELECT * FROM CUSTOMERS WHERE CITY = 'ÝSTANBUL' ORDER BY ID

SELECT * FROM CUSTOMERS  ORDER BY 3,4,1 DESC     -- NUMARALAR  SÜTÜN SAYILARINI TEMSÝL ETMEKTEDÝR...




