SELECT * FROM CUSTOMERS

INSERT INTO CUSTOMERS(CUSTOMERNAME,CITY,DISTRICT,BIRTHDATE,GENDER) VALUES ('Volkan ÇEKÝP','Bartýn','Kurucaþile','1997-10-24 00:00:00.000','E')

DELETE FROM CUSTOMERS

TRUNCATE TABLE CUSTOMERS
