-- ÞEHÝRLERE GÖRE VERÝLEN SÝPARÝÞ MÝKTARLARI

SELECT 
CT.CITY AS SEHIR_ADI,
SUM( OD.LINETOTAL ) AS  TOPLAM_SIPARIS_TUTARI,
SUM(OD.AMOUNT ) AS  TOPLAM_SIPARIS_ADEDI,
COUNT(OD.ID ) AS  TOPLAM_SIPARIS_SAYISI

FROM ORDERS O
INNER JOIN USERS U ON U.ID = O.USERID
INNER JOIN ADDRESS A ON A.ID = O.ADDRESSID
INNER JOIN CITIES CT ON CT.ID = A.CITYID
INNER JOIN TOWNS T ON T.ID = A.TOWNID
INNER JOIN DISTRICTS D ON D.ID = A.DISTRICTID
INNER JOIN PAYMENTS P ON P.ORDERID = O.ID
INNER JOIN INVOICES I ON I.ORDERID = O.ID
INNER JOIN ORDERDETAILS OD ON OD.ORDERID = O.ID
INNER JOIN ITEMS ITM ON ITM.ID = OD.ITEMID

GROUP BY CT.CITY
-- ORDER BY SUM(OD.LINETOTAL) DESC
-- ORDER BY COUNT(OD.ID) DESC
ORDER BY 3 ASC