SELECT U.USERNAME_ AS KULLANICIADI, U.NAMESURNAME AS ADSOYAD, CT.CITY AS ÝLÇE, T.TOWN AS ÝLÇE,
D.DISTRICT AS SEMT, A.ADDRESSTEXT AS AÇIKADRESS, O.ID AS SIPARIS_ID, O. DATE_ AS TARIH, 
O.TOTALPRICE AS TOPLAM_TUTAR, I.DATE_ AS FATURA_TARIHI, I.CARGOFICHENO AS KARGO_FIS_NO,
OD.*, ITM.ITEMCODE AS URUN_KODU, P.DATE_ AS ODEME_TARIHI, P.APPROVECODE AS BANKA_ONAY_KODU,
ITM.ITEMNAME AS URUN_ADI, OD.AMOUNT AS ADET, OD.UNITPRICE AS BIRIM_FIYAT, OD.LINETOTAL AS SATIR_TOPLAMI
FROM ORDERS O
INNER JOIN USERS U ON U.ID = O.USERID
INNER JOIN ADDRESS A ON A.ID = O.ADDRESSID
INNER JOIN CITIES CT ON CT.ID = A.CITYID
INNER JOIN TOWNS T ON T.ID = A.TOWNID
INNER JOIN DISTRICTS D ON D.ID = A.DISTRICTID
INNER JOIN PAYMENTS P ON P.ORDERID = O.ID
INNER JOIN INVOICES I ON I.ORDERID = O.ID
INNER JOIN ORDERDETAILS OD ON OD.ORDERID = O.ID
INNER JOIN ITEMS ITM ON ITM.ID = OD.ITEMID

WHERE -- U.NAMESURNAME  = 'CEYDA GEZGÝNCÝ'
O.ID = 26121