SELECT 
ITM.CATEGORY1 AS KATEGORI_1,ITM.CATEGORY2 AS KATEGORI_2, ITM.CATEGORY3 AS KATEGORI_3,
SUM( OD.LINETOTAL ) AS  TOPLAM_SIPARIS_TUTARI,
SUM(OD.AMOUNT ) AS  TOPLAM_SIPARIS_ADEDI,
COUNT(OD.ID ) AS  TOPLAM_SIPARIS_SAYISI

FROM ORDERS O	
INNER JOIN USERS U ON U.ID = O.USERID
INNER JOIN ADDRESS A ON A.ID = O.ADDRESSID
INNER JOIN CITIES CT ON CT.ID = A.CITYID
INNER JOIN TOWNS T ON T.ID = A.TOWNID
INNER JOIN DISTRICTS D ON D.ID = A.DISTRICTID
INNER JOIN PAYMENTS P ON P.ORDERID = O.ID
INNER JOIN INVOICES I ON I.ORDERID = O.ID
INNER JOIN ORDERDETAILS OD ON OD.ORDERID = O.ID
INNER JOIN ITEMS ITM ON ITM.ID = OD.ITEMID


--WHERE ITM.CATEGORY1 = 'EV'
WHERE ITM.CATEGORY1 = 'KOZMETIK'
GROUP BY ITM.CATEGORY1, ITM.CATEGORY2, ITM.CATEGORY3
ORDER BY 4 DESC