SELECT U.USERNAME_ AS KULLANICIADI, U.NAMESURNAME AS ADSOYAD, CT.CITY AS ÝLÇE, T.TOWN AS ÝLÇE,
D.DISTRICT AS SEMT, A.ADDRESSTEXT AS AÇIKADRESS, O.ID AS SIPARIS_ID, O. DATE_ AS TARIH, 
O.TOTALPRICE AS TOPLAM_TUTAR, I.DATE_ AS FATURA_TARIHI, I.CARGOFICHENO AS KARGO_FIS_NO,
P.DATE_ AS ODEME_TARIHI, P.APPROVECODE AS BANKA_ONAY_KODU
FROM ORDERS O
INNER JOIN USERS U ON U.ID = O.USERID
INNER JOIN ADDRESS A ON A.ID = O.ADDRESSID
INNER JOIN CITIES CT ON CT.ID = A.CITYID
INNER JOIN TOWNS T ON T.ID = A.TOWNID
INNER JOIN DISTRICTS D ON D.ID = A.DISTRICTID
INNER JOIN PAYMENTS P ON P.ORDERID = O.ID
INNER JOIN INVOICES I ON I.ORDERID = O.ID

WHERE U.NAMESURNAME = 'CEYDA GEZGÝNCÝ'
