SELECT * FROM CUSTOMERS WHERE CUSTOMERNAME = 'Irmak TAHSÝNOÐLU'

SELECT * FROM CUSTOMERS WHERE CITY = 'SAMSUN'

SELECT * FROM CUSTOMERS WHERE CITY <> 'ÝZMÝR'

SELECT * FROM CUSTOMERS WHERE NOT CITY = 'SAMSUN'

SELECT BIRTHDATE FROM CUSTOMERS WHERE BIRTHDATE = '19900101'

SELECT * FROM CUSTOMERS WHERE  BIRTHDATE BETWEEN '19900101' AND '20011231'

UPDATE CUSTOMERS SET AGE = DATEDIFF(YEAR, BIRTHDATE, GETDATE())

SELECT * FROM CUSTOMERS WHERE AGE BETWEEN 23 AND 32

SELECT * FROM CUSTOMERS WHERE CUSTOMERNAME LIKE '%ALÝ%'

SELECT * FROM CUSTOMERS WHERE CUSTOMERNAME NOT LIKE 'M%'

SELECT * FROM CUSTOMERS WHERE CITY IN ('ÝSTANBUL' , 'ANKARA' , 'ÝZMÝR', 'BURSA')

UPDATE CUSTOMERS SET GENDER = 'ERKEK' WHERE GENDER = 'E'
UPDATE CUSTOMERS SET GENDER = 'KADIN' WHERE GENDER = 'K'

SELECT * FROM CUSTOMERS WHERE ID = 18

DELETE FROM CUSTOMERS WHERE ID = 18


